### ISSUE TITLE
Setting up kanban board

### ISSUE THREAD

**Issue by sjdev2212** [algerina/recipeApp#18]
This issue is created to show how we are going to distribute the amount of work for this capstone.
Here is the link [https://github.com/algerina/recipeApp/projects/1](url)
We are two people working in this group.

**Comment by DeliceLydia** [comment]
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
- [x] Please give your cards a descriptive title it's not necessary to add a name on
the card title for example instead of `Anibal create login page` you can just make it `Create login page` 
because we can see from the Avatar who created it
- [x] Please create a card for N+1 queries
- [x] Please create a card for the navigation menu that allows users to open all of the pages you created.


### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by t-yanick** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

### OPTIONAL 
- Please it will be nice to delete cards that are not related to the project as this will be make you kanban board less crowded. Please kindly delete the first three cards as they are not related to the project. 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
